/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	Item:{
		renferencedItems:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		referencedBy:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Query:{
		item:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		items:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:true
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Type:{
		renferencedItems:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		referencedBy:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Text:{
		renferencedItems:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		referencedBy:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Date:{
		renferencedItems:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		referencedBy:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Title:{
		renferencedItems:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		referencedBy:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Topic:{
		renferencedItems:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		referencedBy:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Task:{
		renferencedItems:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		referencedBy:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	List:{
		renferencedItems:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		referencedBy:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Webpage:{
		renferencedItems:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		referencedBy:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Note:{
		renferencedItems:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		referencedBy:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Status:{
		renferencedItems:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		referencedBy:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Book:{
		renferencedItems:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		referencedBy:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	Movie:{
		renferencedItems:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		referencedBy:{
			type:{
				type:"ItemType",
				array:false,
				arrayRequired:false,
				required:false
			},
			first:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			after:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	ItemType: "enum"
}

export const ReturnTypes: Record<string,any> = {
	Item:{
		"...on Type": "Type",
		"...on Text": "Text",
		"...on Date": "Date",
		"...on Title": "Title",
		"...on Topic": "Topic",
		"...on Task": "Task",
		"...on List": "List",
		"...on Webpage": "Webpage",
		"...on Note": "Note",
		"...on Status": "Status",
		"...on Book": "Book",
		"...on Movie": "Movie",
		id:"ID",
		renferencedItems:"References",
		referencedBy:"References",
		types:"ItemType",
		metadata:"String"
	},
	References:{
		references:"Reference",
		pageInfo:"PageInfo"
	},
	PageInfo:{
		hasNextPage:"Boolean"
	},
	Reference:{
		cursor:"String",
		item:"Item"
	},
	Query:{
		item:"Item",
		items:"References"
	},
	Type:{
		id:"ID",
		renferencedItems:"References",
		referencedBy:"References",
		types:"ItemType",
		metadata:"String",
		value:"String"
	},
	Text:{
		id:"ID",
		renferencedItems:"References",
		referencedBy:"References",
		types:"ItemType",
		metadata:"String",
		value:"String"
	},
	Date:{
		id:"ID",
		renferencedItems:"References",
		referencedBy:"References",
		types:"ItemType",
		metadata:"String"
	},
	Title:{
		id:"ID",
		renferencedItems:"References",
		referencedBy:"References",
		types:"ItemType",
		metadata:"String"
	},
	Topic:{
		id:"ID",
		renferencedItems:"References",
		referencedBy:"References",
		types:"ItemType",
		metadata:"String"
	},
	Task:{
		id:"ID",
		renferencedItems:"References",
		referencedBy:"References",
		types:"ItemType",
		metadata:"String"
	},
	List:{
		id:"ID",
		renferencedItems:"References",
		referencedBy:"References",
		types:"ItemType",
		metadata:"String"
	},
	Webpage:{
		id:"ID",
		renferencedItems:"References",
		referencedBy:"References",
		types:"ItemType",
		metadata:"String"
	},
	Note:{
		id:"ID",
		renferencedItems:"References",
		referencedBy:"References",
		types:"ItemType",
		metadata:"String"
	},
	Status:{
		id:"ID",
		renferencedItems:"References",
		referencedBy:"References",
		types:"ItemType",
		metadata:"String"
	},
	Book:{
		id:"ID",
		renferencedItems:"References",
		referencedBy:"References",
		types:"ItemType",
		metadata:"String"
	},
	Movie:{
		id:"ID",
		renferencedItems:"References",
		referencedBy:"References",
		types:"ItemType",
		metadata:"String"
	}
}